### ISSUE TITLE
Error when running the BDSP_RNG Script

### ISSUE THREAD

**Issue by jdjmad** [Real96/BDSP-CheatEngine-Lua#3]
I have followed the readme file to try and get this cheat engine to work on my copy of pokemon shining pearl v 1.3 on both yuzu and ryujinx. I created a new save and went through character creation, saved and reset to be able to pause the game at the title screen. After checking MEM_MAPPED and opening the process, I opened the table and added the code from the BDSP_RNG 1.3 to the script and ran it. It runs, but I get the following error.

Error:[string "-- Various variables..."]:48: attempt to perform arithmetic on a nil value (local 'playerPrefsProviderInstanceAddr')

I'm not sure what I'm doing wrong that this isn't working. Any help is appreciated.

![Screenshot 2024-03-07 111033](https://github.com/Real96/BDSP-CheatEngine-Lua/assets/162605319/640b474f-3e43-4c07-b2b1-c97b5d008aef)
![Screenshot 2024-03-07 111053](https://github.com/Real96/BDSP-CheatEngine-Lua/assets/162605319/80ef0315-2f53-4a57-9e19-27945439dbdf)
![Screenshot 2024-03-07 111112](https://github.com/Real96/BDSP-CheatEngine-Lua/assets/162605319/633d6258-56ea-49bc-ac6e-9fdc52983897)
![Screenshot 2024-03-07 111131](https://github.com/Real96/BDSP-CheatEngine-Lua/assets/162605319/11a68880-23db-40d9-a3af-c839779e2c32)

**Comment by Real96** [comment]
Pushed the fix. Pls try it on latest Ryujinx/yuzu version

**Comment by jdjmad** [comment]
> Pushed the fix. Pls try it on latest Ryujinx/yuzu version

Works perfectly! Thank you.
