### ISSUE TITLE
Error:[string "-- Various variables ..."]:55: attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by JamieCee20** [Real96/BDSP-CheatEngine-Lua#4]
Cop-ying the contents of the latest file and execute gives me this error

**Comment by Real96** [comment]
> Cop-ying the contents of the latest file and execute gives me this error

Which emu? Which release?

**Comment by JamieCee20** [comment]
> > Cop-ying the contents of the latest file and execute gives me this error
> 
> Which emu? Which release?

Using yuzu and v1.3.0

**Comment by Real96** [comment]
> > > Cop-ying the contents of the latest file and execute gives me this error
> > 
> > 
> > Which emu? Which release?
> 
> Using yuzu and v1.3.0

Which yuzu release?

**Comment by Real96** [comment]
I'm not able to reproduce on latest yuzu release. Be sure to use [yuzu scripts](https://github.com/Real96/BDSP-CheatEngine-Lua/tree/main/yuzu), correct version matching game version. In case the error persists also on latest yuzu release, i'll reopen. Feel free to comment again here

**Comment by Epirei** [comment]
same issue with ryujinx and 1.3.0

**Comment by Real96** [comment]
> same issue with ryujinx and 1.3.0

Update to latest ryujinx release and use latest commit luas
